CREATE SEQUENCE "SYSDBA"."NUTRITION_RECOMMENDATION_SEQ"
INCREMENT BY 1
START WITH 34
MAXVALUE 9223372036854775807
MINVALUE 1;
CREATE SEQUENCE "SYSDBA"."SEQ_FOOD_ID"
INCREMENT BY 1
START WITH 82
MAXVALUE 9223372036854775807
MINVALUE 1
CACHE 20;
CREATE SEQUENCE "SYSDBA"."SEQ_HEALTH_MODEL_CONFIG_ID"
INCREMENT BY 1
START WITH 2
MAXVALUE 9223372036854775807
MINVALUE 1
CACHE 20;
CREATE SEQUENCE "SYSDBA"."SEQ_USER_ID"
INCREMENT BY 1
START WITH 2
MAXVALUE 9223372036854775807
MINVALUE 1
CACHE 20;
CREATE SEQUENCE "SYSDBA"."USER_FOOD_RECORD_SEQ"
INCREMENT BY 1
START WITH 34
MAXVALUE 9223372036854775807
MINVALUE 1;
CREATE SEQUENCE "SYSDBA"."USER_NUTRITION_TARGET_SEQ"
INCREMENT BY 1
START WITH 4
MAXVALUE 9223372036854775807
MINVALUE 1;
CREATE TABLE "SYSDBA"."EVALUATIONS"
(
 "ID" BIGINT IDENTITY(170,1) NOT NULL,
 "PARENT_ID" BIGINT NULL,
 "COMMENTER_ID" BIGINT NULL,
 "REPLIER_ID" BIGINT NULL,
 "CONTENT_TYPE" VARCHAR(100 char) NULL,
 "CONTENT_ID" BIGINT NULL,
 "CONTENT" VARCHAR(255 char) NULL,
 "UPVOTE_LIST" CLOB NULL,
 "CREATE_TIME" TIMESTAMP(0) NULL
);
CREATE TABLE "SYSDBA"."FOOD"
(
 "ID" INTEGER NOT NULL,
 "FOOD_NAME" VARCHAR(100) NOT NULL,
 "SERVING_SIZE" DECIMAL(8,2) DEFAULT 100
 NULL,
 "SERVING_UNIT" VARCHAR(20) DEFAULT '克'
 NULL,
 "CALORIES" DECIMAL(8,2) NOT NULL,
 "PROTEIN" DECIMAL(8,2) DEFAULT 0
 NULL,
 "CARBOHYDRATE" DECIMAL(8,2) DEFAULT 0
 NULL,
 "FAT" DECIMAL(8,2) DEFAULT 0
 NULL,
 "FIBER" DECIMAL(8,2) DEFAULT 0
 NULL,
 "SODIUM" DECIMAL(8,2) DEFAULT 0
 NULL,
 "SOURCE" VARCHAR(100) NULL,
 "CREATE_TIME" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
 NULL
);
CREATE TABLE "SYSDBA"."HEALTH_MODEL_CONFIG"
(
 "ID" BIGINT IDENTITY(18,1) NOT NULL,
 "USER_ID" BIGINT NULL,
 "NAME" VARCHAR(255 char) NULL,
 "DETAIL" VARCHAR(255 char) NULL,
 "COVER" VARCHAR(255 char) NULL,
 "UNIT" VARCHAR(255 char) NULL,
 "SYMBOL" VARCHAR(255 char) NULL,
 "IS_GLOBAL" TINYINT NULL,
 "VALUE_RANGE" VARCHAR(255 char) NULL
);
CREATE TABLE "SYSDBA"."MESSAGE"
(
 "ID" BIGINT IDENTITY(100,1) NOT NULL,
 "CONTENT" VARCHAR(255 char) NULL,
 "MESSAGE_TYPE" INT NULL,
 "RECEIVER_ID" BIGINT NULL,
 "SENDER_ID" BIGINT NULL,
 "IS_READ" TINYINT NULL,
 "CONTENT_ID" INT NULL,
 "CREATE_TIME" TIMESTAMP(0) NULL
);
CREATE TABLE "SYSDBA"."NEWS"
(
 "ID" BIGINT IDENTITY(32,1) NOT NULL,
 "NAME" VARCHAR(255 char) NULL,
 "CONTENT" CLOB NULL,
 "TAG_ID" BIGINT NULL,
 "COVER" VARCHAR(255 char) NULL,
 "IS_TOP" TINYINT NULL,
 "CREATE_TIME" TIMESTAMP(0) NULL,
 "PUBLISHER" BIGINT NULL,
 "VIEWS_NUMBER" NUMBER(10,0) DEFAULT 0
 NULL
);
CREATE TABLE "SYSDBA"."NEWS_SAVE"
(
 "ID" BIGINT IDENTITY(59,1) NOT NULL,
 "USER_ID" BIGINT NULL,
 "NEWS_ID" BIGINT NULL,
 "CREATE_TIME" TIMESTAMP(0) NULL
);
CREATE TABLE "SYSDBA"."NUTRITION_RECOMMENDATION"
(
 "ID" INTEGER NOT NULL,
 "USER_ID" BIGINT NOT NULL,
 "RECOMMENDATION_DATE" DATE NOT NULL,
 "CALORIES" INTEGER NOT NULL,
 "PROTEIN" DECIMAL(10,2) NOT NULL,
 "CARBOHYDRATE" DECIMAL(10,2) NOT NULL,
 "FAT" DECIMAL(10,2) NOT NULL,
 "FIBER" DECIMAL(10,2) NULL,
 "SODIUM" DECIMAL(10,2) NULL,
 "RECOMMENDATION_TYPE" VARCHAR(20) NOT NULL,
 "NOTES" VARCHAR(10000) NULL,
 "CREATE_TIME" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
 NULL
);
CREATE TABLE "SYSDBA"."TAGS"
(
 "ID" BIGINT IDENTITY(20,1) NOT NULL,
 "NAME" VARCHAR(255 char) NULL
);
CREATE TABLE "SYSDBA"."USER"
(
 "ID" BIGINT IDENTITY(28,1) NOT NULL,
 "USER_ACCOUNT" VARCHAR(50 char) NULL,
 "USER_NAME" VARCHAR(50 char) NULL,
 "USER_PWD" VARCHAR(100 char) NULL,
 "USER_AVATAR" VARCHAR(255 char) NULL,
 "USER_EMAIL" VARCHAR(50 char) NULL,
 "USER_ROLE" INT NULL,
 "IS_LOGIN" TINYINT NULL,
 "IS_WORD" TINYINT NULL,
 "CREATE_TIME" TIMESTAMP(0) NULL,
 "BIRTH_DATE" DATE NULL,
 "GENDER" VARCHAR(10) NULL
);
CREATE TABLE "SYSDBA"."USER_FOOD_RECORD"
(
 "ID" INTEGER NOT NULL,
 "USER_ID" BIGINT NOT NULL,
 "FOOD_ID" INTEGER NOT NULL,
 "RECORD_DATE" DATE NOT NULL,
 "MEAL_TYPE" INTEGER NOT NULL,
 "CONSUME_AMOUNT" DECIMAL(8,2) NOT NULL,
 "ACTUAL_CALORIES" DECIMAL(8,2) NULL,
 "ACTUAL_PROTEIN" DECIMAL(8,2) NULL,
 "ACTUAL_CARBOHYDRATE" DECIMAL(8,2) NULL,
 "ACTUAL_FAT" DECIMAL(8,2) NULL,
 "NOTES" VARCHAR(200) NULL,
 "CREATE_TIME" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
 NULL
);
CREATE TABLE "SYSDBA"."USER_HEALTH"
(
 "ID" BIGINT IDENTITY(98,1) NOT NULL,
 "USER_ID" BIGINT NULL,
 "HEALTH_MODEL_CONFIG_ID" BIGINT NULL,
 "VALUE" VARCHAR(255 char) NULL,
 "CREATE_TIME" TIMESTAMP(0) NULL
);
CREATE GLOBAL TEMPORARY  TABLE "SYSDBA"."##HISTOGRAMS_TABLE"
(
 "OWNER" VARCHAR(128) NULL,
 "TABLE_NAME" VARCHAR(128) NULL,
 "COLUMN_NAME" VARCHAR(128) NULL,
 "HISTOGRAM" VARCHAR(15) NULL,
 "ENDPOINT_VALUE" VARCHAR(128) NULL,
 "ENDPOINT_HEIGHT" BIGINT NULL,
 "ENDPOINT_KEYHEIGHT" BIGINT NULL,
 "ENDPOINT_DISTINCT" BIGINT NULL
) ON COMMIT DELETE ROWS ;
ALTER TABLE "SYSDBA"."EVALUATIONS" ADD CONSTRAINT  NOT CLUSTER  PRIMARY KEY("ID") ;
ALTER TABLE "SYSDBA"."FOOD" ADD CONSTRAINT  NOT CLUSTER  PRIMARY KEY("ID") ;
ALTER TABLE "SYSDBA"."HEALTH_MODEL_CONFIG" ADD CONSTRAINT  NOT CLUSTER  PRIMARY KEY("ID") ;
ALTER TABLE "SYSDBA"."MESSAGE" ADD CONSTRAINT  NOT CLUSTER  PRIMARY KEY("ID") ;
ALTER TABLE "SYSDBA"."NEWS" ADD CONSTRAINT  NOT CLUSTER  PRIMARY KEY("ID") ;
ALTER TABLE "SYSDBA"."NEWS_SAVE" ADD CONSTRAINT  NOT CLUSTER  PRIMARY KEY("ID") ;
ALTER TABLE "SYSDBA"."NUTRITION_RECOMMENDATION" ADD CONSTRAINT  NOT CLUSTER  PRIMARY KEY("ID") ;
ALTER TABLE "SYSDBA"."TAGS" ADD CONSTRAINT  NOT CLUSTER  PRIMARY KEY("ID") ;
ALTER TABLE "SYSDBA"."USER" ADD CONSTRAINT  NOT CLUSTER  PRIMARY KEY("ID") ;
ALTER TABLE "SYSDBA"."USER_FOOD_RECORD" ADD CONSTRAINT  NOT CLUSTER  PRIMARY KEY("ID") ;
ALTER TABLE "SYSDBA"."USER_HEALTH" ADD CONSTRAINT  NOT CLUSTER  PRIMARY KEY("ID") ;
ALTER TABLE "SYSDBA"."EVALUATIONS" ADD CONSTRAINT "FK_EVALUATIONS_COMMENTER_ID" FOREIGN KEY("COMMENTER_ID") REFERENCES "SYSDBA"."USER"("ID") ;
ALTER TABLE "SYSDBA"."EVALUATIONS" ADD CONSTRAINT "FK_EVALUATIONS_REPLIER_ID" FOREIGN KEY("REPLIER_ID") REFERENCES "SYSDBA"."USER"("ID") ;
ALTER TABLE "SYSDBA"."EVALUATIONS" ADD CONSTRAINT "FK_EVALUATIONS_PARENT_ID" FOREIGN KEY("PARENT_ID") REFERENCES "SYSDBA"."EVALUATIONS"("ID") with index ;
ALTER TABLE "SYSDBA"."HEALTH_MODEL_CONFIG" ADD CONSTRAINT "FK_HEALTH_MODEL_CONFIG_USER_ID" FOREIGN KEY("USER_ID") REFERENCES "SYSDBA"."USER"("ID") ;
ALTER TABLE "SYSDBA"."MESSAGE" ADD CONSTRAINT "FK_MESSAGE_RECEIVER_ID" FOREIGN KEY("RECEIVER_ID") REFERENCES "SYSDBA"."USER"("ID") ;
ALTER TABLE "SYSDBA"."MESSAGE" ADD CONSTRAINT "FK_MESSAGE_SENDER_ID" FOREIGN KEY("SENDER_ID") REFERENCES "SYSDBA"."USER"("ID") ;
ALTER TABLE "SYSDBA"."NEWS" ADD CONSTRAINT "FK_NEWS_TAG_ID" FOREIGN KEY("TAG_ID") REFERENCES "SYSDBA"."TAGS"("ID") ;
ALTER TABLE "SYSDBA"."NEWS" ADD CONSTRAINT "FK_NEWS_PUBLISHER" FOREIGN KEY("PUBLISHER") REFERENCES "SYSDBA"."USER"("ID") ;
ALTER TABLE "SYSDBA"."NEWS_SAVE" ADD CONSTRAINT "FK_NEWS_SAVE_NEWS_ID" FOREIGN KEY("NEWS_ID") REFERENCES "SYSDBA"."NEWS"("ID") ;
ALTER TABLE "SYSDBA"."NEWS_SAVE" ADD CONSTRAINT "FK_NEWS_SAVE_USER_ID" FOREIGN KEY("USER_ID") REFERENCES "SYSDBA"."USER"("ID") ;
ALTER TABLE "SYSDBA"."NUTRITION_RECOMMENDATION" ADD CONSTRAINT "FK_NUTRITION_RECOMMENDATION_USER_ID" FOREIGN KEY("USER_ID") REFERENCES "SYSDBA"."USER"("ID") ;
ALTER TABLE "SYSDBA"."USER_FOOD_RECORD" ADD CONSTRAINT "FK_USER_FOOD_RECORD_USER_ID" FOREIGN KEY("USER_ID") REFERENCES "SYSDBA"."USER"("ID") ;
ALTER TABLE "SYSDBA"."USER_FOOD_RECORD" ADD CONSTRAINT "FK_USER_FOOD_RECORD_FOOD_ID" FOREIGN KEY("FOOD_ID") REFERENCES "SYSDBA"."FOOD"("ID") ;
ALTER TABLE "SYSDBA"."USER_HEALTH" ADD CONSTRAINT "FK_USER_HEALTH_MODEL_CONFIG_ID" FOREIGN KEY("HEALTH_MODEL_CONFIG_ID") REFERENCES "SYSDBA"."HEALTH_MODEL_CONFIG"("ID") ;
ALTER TABLE "SYSDBA"."USER_HEALTH" ADD CONSTRAINT "FK_USER_HEALTH_USER_ID" FOREIGN KEY("USER_ID") REFERENCES "SYSDBA"."USER"("ID") ;
COMMENT ON COLUMN "SYSDBA"."EVALUATIONS"."COMMENTER_ID" IS '评论者ID';
COMMENT ON COLUMN "SYSDBA"."EVALUATIONS"."CONTENT" IS '评论内容';
COMMENT ON COLUMN "SYSDBA"."EVALUATIONS"."CONTENT_ID" IS '内容ID';
COMMENT ON COLUMN "SYSDBA"."EVALUATIONS"."CONTENT_TYPE" IS '内容类型';
COMMENT ON COLUMN "SYSDBA"."EVALUATIONS"."CREATE_TIME" IS '评论时间';
COMMENT ON COLUMN "SYSDBA"."EVALUATIONS"."ID" IS '主键';
COMMENT ON COLUMN "SYSDBA"."EVALUATIONS"."PARENT_ID" IS '父级评论ID';
COMMENT ON COLUMN "SYSDBA"."EVALUATIONS"."REPLIER_ID" IS '回复者ID';
COMMENT ON COLUMN "SYSDBA"."EVALUATIONS"."UPVOTE_LIST" IS '点赞列表，以","分割';
COMMENT ON TABLE "SYSDBA"."HEALTH_MODEL_CONFIG" IS '健康模型表';
COMMENT ON COLUMN "SYSDBA"."HEALTH_MODEL_CONFIG"."COVER" IS '配置图标';
COMMENT ON COLUMN "SYSDBA"."HEALTH_MODEL_CONFIG"."DETAIL" IS '配置简介';
COMMENT ON COLUMN "SYSDBA"."HEALTH_MODEL_CONFIG"."ID" IS '健康模型自增主键';
COMMENT ON COLUMN "SYSDBA"."HEALTH_MODEL_CONFIG"."IS_GLOBAL" IS '是否是全局模型';
COMMENT ON COLUMN "SYSDBA"."HEALTH_MODEL_CONFIG"."NAME" IS '配置名';
COMMENT ON COLUMN "SYSDBA"."HEALTH_MODEL_CONFIG"."SYMBOL" IS '配置符号';
COMMENT ON COLUMN "SYSDBA"."HEALTH_MODEL_CONFIG"."UNIT" IS '配置单位';
COMMENT ON COLUMN "SYSDBA"."HEALTH_MODEL_CONFIG"."USER_ID" IS '用户ID';
COMMENT ON COLUMN "SYSDBA"."HEALTH_MODEL_CONFIG"."VALUE_RANGE" IS '正常值范围';
COMMENT ON COLUMN "SYSDBA"."MESSAGE"."CONTENT" IS '消息内容（消息体）';
COMMENT ON COLUMN "SYSDBA"."MESSAGE"."CONTENT_ID" IS '关联的内容ID';
COMMENT ON COLUMN "SYSDBA"."MESSAGE"."CREATE_TIME" IS '消息的发送时间';
COMMENT ON COLUMN "SYSDBA"."MESSAGE"."ID" IS '消息表的自增主键ID';
COMMENT ON COLUMN "SYSDBA"."MESSAGE"."IS_READ" IS '消息是否已经阅读';
COMMENT ON COLUMN "SYSDBA"."MESSAGE"."MESSAGE_TYPE" IS '消息类型（指标数据、互动、系统消息...）';
COMMENT ON COLUMN "SYSDBA"."MESSAGE"."RECEIVER_ID" IS '接收者ID';
COMMENT ON COLUMN "SYSDBA"."MESSAGE"."SENDER_ID" IS '发送者ID';
COMMENT ON TABLE "SYSDBA"."NEWS" IS '健康资讯表';
COMMENT ON COLUMN "SYSDBA"."NEWS"."CONTENT" IS '内容';
COMMENT ON COLUMN "SYSDBA"."NEWS"."COVER" IS '图片封面';
COMMENT ON COLUMN "SYSDBA"."NEWS"."CREATE_TIME" IS '发布时间';
COMMENT ON COLUMN "SYSDBA"."NEWS"."ID" IS '健康资讯ID';
COMMENT ON COLUMN "SYSDBA"."NEWS"."IS_TOP" IS '是否推荐';
COMMENT ON COLUMN "SYSDBA"."NEWS"."NAME" IS '标题';
COMMENT ON COLUMN "SYSDBA"."NEWS"."TAG_ID" IS '标签ID';
COMMENT ON TABLE "SYSDBA"."NEWS_SAVE" IS '健康资讯收藏表';
COMMENT ON COLUMN "SYSDBA"."NEWS_SAVE"."CREATE_TIME" IS '收藏的时间';
COMMENT ON COLUMN "SYSDBA"."NEWS_SAVE"."ID" IS '资讯的收藏ID';
COMMENT ON COLUMN "SYSDBA"."NEWS_SAVE"."NEWS_ID" IS '资讯ID';
COMMENT ON COLUMN "SYSDBA"."NEWS_SAVE"."USER_ID" IS '用户ID';
COMMENT ON TABLE "SYSDBA"."TAGS" IS '标签分类表';
COMMENT ON COLUMN "SYSDBA"."TAGS"."ID" IS '标签ID';
COMMENT ON COLUMN "SYSDBA"."TAGS"."NAME" IS '标签分类名';
COMMENT ON COLUMN "SYSDBA"."USER"."CREATE_TIME" IS '用户注册时间';
COMMENT ON COLUMN "SYSDBA"."USER"."ID" IS '用户编号';
COMMENT ON COLUMN "SYSDBA"."USER"."IS_LOGIN" IS '可登录状态(0：可用，1：不可用)';
COMMENT ON COLUMN "SYSDBA"."USER"."IS_WORD" IS '禁言状态(0：可用，1：不可用)';
COMMENT ON COLUMN "SYSDBA"."USER"."USER_ACCOUNT" IS '用户账号';
COMMENT ON COLUMN "SYSDBA"."USER"."USER_AVATAR" IS '用户头像';
COMMENT ON COLUMN "SYSDBA"."USER"."USER_EMAIL" IS '用户邮箱';
COMMENT ON COLUMN "SYSDBA"."USER"."USER_NAME" IS '用户昵称';
COMMENT ON COLUMN "SYSDBA"."USER"."USER_PWD" IS '用户密码';
COMMENT ON COLUMN "SYSDBA"."USER"."USER_ROLE" IS '用户角色';
COMMENT ON TABLE "SYSDBA"."USER_HEALTH" IS '用户健康记录表';
COMMENT ON COLUMN "SYSDBA"."USER_HEALTH"."CREATE_TIME" IS '记录时间';
COMMENT ON COLUMN "SYSDBA"."USER_HEALTH"."HEALTH_MODEL_CONFIG_ID" IS '健康模型ID';
COMMENT ON COLUMN "SYSDBA"."USER_HEALTH"."ID" IS '用户健康记录主键';
COMMENT ON COLUMN "SYSDBA"."USER_HEALTH"."USER_ID" IS '用户ID';
COMMENT ON COLUMN "SYSDBA"."USER_HEALTH"."VALUE" IS '输入的值';
CREATE TRIGGER "SYSDBA"."TRG_FOOD_ID"
 BEFORE  INSERT 
 ON "SYSDBA"."FOOD" 
 referencing OLD ROW AS "OLD" NEW ROW AS "NEW"

 for each row
 
BEGIN
    SELECT SYSDBA.SEQ_FOOD_ID.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
CREATE TRIGGER "SYSDBA"."TRG_HEALTH_MODEL_CONFIG_ID"
 BEFORE  INSERT 
 ON "SYSDBA"."HEALTH_MODEL_CONFIG" 
 referencing OLD ROW AS "OLD" NEW ROW AS "NEW"

 for each row

when (NEW.ID IS NULL)

BEGIN
    SELECT SYSDBA.SEQ_HEALTH_MODEL_CONFIG_ID.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
CREATE TRIGGER "SYSDBA"."TRG_USER_ID"
 BEFORE  INSERT 
 ON "SYSDBA"."USER" 
 referencing OLD ROW AS "OLD" NEW ROW AS "NEW"

 for each row

when (NEW.ID IS NULL)

BEGIN
    SELECT SYSDBA.SEQ_USER_ID.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
