-- 创建用户营养目标表
CREATE TABLE SYSDBA.USER_NUTRITION_TARGET (
    ID INTEGER PRIMARY KEY,
    USER_ID INTEGER NOT NULL,
    CALORIES INTEGER NOT NULL,
    PROTEIN DECIMAL(10,2) NOT NULL,
    CARBOHYDRATE DECIMAL(10,2) NOT NULL,
    FAT DECIMAL(10,2) NOT NULL,
    FIBER DECIMAL(10,2),
    SODIUM DECIMAL(10,2),
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP,
    CONSTRAINT FK_USER_NUTRITION_TARGET_USER_ID FOREIGN KEY (USER_ID) REFERENCES SYSDBA."USER"(ID)
);